### ISSUE TITLE
Mod update notice

### ISSUE THREAD

**Issue by MTXPapa** [mactso/VillagersRespawn#1]
Thanks for creating this mod.  I notice that when I start the Minecraft launcher and it loads all of my mods, the MODS button always shows that your mod has an update available.  When I check to update VillagersRespawn it is the current version that I have loaded. I am loading 104 mods and yours is the only one that does this.  Is there a way to show that the mod is up to date?

I really appreciate all the time you incur in creating mods as well as all the other mod-makers out there.  You bring great fun for all of us playing the game.

**Comment by mactso** [comment]
what version do you have 1.16.4??  I might have an issue with the update file location or with the name or version number.
I'll give it a look.

I really appreciate the feedback.  Giving it a look now to make sure I don't see anything obvious.

Okay so the current version is :VillagersRespawn-1.16.4-1.16.4-1.35.0.3.jar

Checking the update notice file...
Okay.. it said VillagersRespawn-1.16.4-1.16.4-1.**_34_**.0.3.jar

I've changed the 34 to 35 (for Forge 35) and checked in the changes.   If this didnt' resolve the issue please let me know.

**Comment by MTXPapa** [comment]
Yes, running 1.16.4

**Comment by mactso** [comment]
This should be fixed.
I double checked just now and the current version and the version in the update file are the same.

**Comment by MTXPapa** [comment]
I'm getting the same result as before, after the Minecraft Launcher finishes loading, the "Mod" button shows the Green light indicating that there is an update available.  When I click on the Mod button and scroll down through the mods I am using, your mod has the green light next to it indicating I need to update it.  When I go to your downloads it is showing that I have the current version loaded.
I'm not a mod maker and do not know anything about how you make them but there must be something in the code that is saying that VillagerRespawn is not at the latest update available.

**Comment by rex706** [comment]
Can confirm this is still an issue with the latest 1.16.4 version 1.35.0.3

![image](https://user-images.githubusercontent.com/15636269/104752801-215bc180-5725-11eb-8102-0bc18af294e6.png)

**Comment by MTXPapa** [comment]
Yes, this issue remains the same.  Minecraft 116.4, using 1.16.4 version 1.35.0.3 of VillagersRespawn, makes the Mod Light  turn on, even though this mod is up to date.  The same thing happens to another of the owners mods - Regrowth.  Something is being left out of the codes that turns out that green light in the Launchers MOD section when these mods are up to date.  None of the other 109 mods I am using are doing this.  Usually if that green mod light is on, there is a mod that needs to be updated.  When the user clicks on the mod button in the Minecraft Launcher, it shows all the mods that have loaded, and if any mod has an update available, the green light will go on next to that mod, to alert the user to update that mod.  Mac Tso has several mods and I am using 2 of his now.  Both of those mods make the mod button green light glow when both mods are up to date.

**Comment by mactso** [comment]
I'll try to give this a look this weekend.  Was up overnight working on the gurty.
Not sure why this one mod has a problem.

Thanks for raising the issue tho!

**Comment by MTXPapa** [comment]
I upgraded to Minecraft 1.16.5 and this problem has gone away.  Thank you again for being a mod maker. I am also using your Regrowth mod.

**Comment by mactso** [comment]
Okay- this is resolved.

The "update" file had rolled back to a prior version when I had a github issue a few weeks ago.
The update file is now correct for 1.16.3 to 1.16.5.
